rakutentech/laravel-request-docs

README.md, config/request-docs.php, resources/views/index.blade.php, src/Commands/LaravelRequestDocsCommand.php, src/Controllers/LaravelRequestDocsController.php, src/LaravelRequestDocs.php
Add Cancel Request Button + Add Bearer Token If The URL Need Auth + Show Only Controller Name Not Full Path
=> Add Features

src/LaravelRequestDocs.php
There were many foreach loops with the same logic in sortDocs method. This PR refactors them.
=> Refactor sortDocs

composer.json
Puts back https://github.com/rakutentech/laravel-request-docs/commit/cb569fb007475e71da56f0966ff8efd172c32fcb
=> Fixes #39: lost commit?

README.md, config/request-docs.php, examples/postman.sample.json, resources/views/index.blade.php, src/Commands/LaravelRequestDocsCommand.php, src/Controllers/LaravelRequestDocsController.php, src/LaravelRequestDocsToOpenApi.php, tests/LRDOpenApiTest.php, tests/TestCase.php
Fixes #10 
The feature exports basic routes, rules definition for GET|POST|PUT|DELETE requests that can be exported to open API specification via URL or cli
=> open api 3.0.0 support. Fixes #10

resources/views/index.blade.php, src/LaravelRequestDocsToOpenApi.php
Added support for `boolean` and `file|image` attribute types
=> Added boolean and file attribute type support

resources/views/index.blade.php
This is probably the next most common type.  I've kept the color blue not knowing what you'd want to do there.
=> Adding numeric and JSON as types

resources/views/index.blade.php
- Search only work for api route 
- I have added search with dock block or description because some cases user add the description on controller action so he need to search by description
=> User can search by description or doc bolck also

README.md, package-lock.json, package.json, ui/src/components/ApiAction.tsx, ui/src/components/ApiInfo.tsx, ui/src/components/App.tsx, ui/src/components/Sidebar.tsx, ui/src/components/TopNav.tsx, ui/src/components/elements/ApiActionInfo.tsx, ui/src/components/elements/ApiActionLog.tsx, ui/src/components/elements/ApiActionRequest.tsx, ui/src/components/elements/ApiActionResponse.tsx, ui/src/components/elements/ApiActionSQL.tsx, ui/src/components/elements/ApiActionTabs.tsx, ui/src/global.css, ui/src/libs/constants.tsx, ui/src/libs/strings.tsx, ui/src/libs/types.tsx
(v2.3) bug fix where localstorage caused tabs to not switch back
(v2.3) search has icon
(v2.3) elements and icons
(v2.3) elements request action
(v2.3) elements tabs
(v2.3) elements
(v2.3) moved to lib
(v2.3) files
=> (v2.3) UI Bug fixes and major refactor. Icons everywhere. Local storage bug fixed.

ui/astro.config.mjs, ui/package-lock.json, ui/package.json, ui/src/components/App.tsx, ui/src/components/TopNav.tsx, ui/src/components/elements/ApiActionCurl.tsx, ui/src/components/elements/ApiActionInfo.tsx
=> (v2.4) adds version on nav and fixes curl command

README.md, config/request-docs.php, src/LaravelRequestDocsMiddleware.php, ui/src/components/ApiAction.tsx, ui/src/components/ApiInfo.tsx, ui/src/components/TopNav.tsx, ui/src/components/elements/ApiActionEvents.tsx, ui/src/components/elements/ApiActionLog.tsx, ui/src/components/elements/ApiActionTabs.tsx, ui/src/global.css
=> (v2.7) Show Models activity upon api request 

README.md, src/LaravelRequestDocsMiddleware.php, ui/src/components/ApiAction.tsx, ui/src/components/ApiInfo.tsx, ui/src/components/App.tsx, ui/src/components/elements/ApiActionEvents.tsx, ui/src/components/elements/ApiActionInfo.tsx, ui/src/components/elements/ApiActionRequest.tsx, ui/src/global.css
=> (v2.8) fixes display bugs, timeline for model events, update screenshots

ui/src/components/ApiAction.tsx, ui/src/components/elements/ApiActionEvents.tsx
Fixes: #169 
Fixes: Adds icons to timeline
=> (v2.10) timeline has icons

src/LaravelRequestDocs.php, tests/mocks/lrd-response.json, ui/src/components/ApiAction.tsx, ui/src/components/App.tsx, ui/src/components/Sidebar.tsx
=> Fixes #211 #212 #215 - where anchor link, markdown indentation and pagination didn't work as intended

ui/src/components/App.tsx, ui/src/components/Sidebar.tsx, ui/src/global.css
Fixes #217 #194 
```
+ offset={() => 120}
- setTimeout(() => {window.scrollBy(0, -128)}, 600); 
```
@MizouziE
=> Fixed header

ui/src/global.css
=> ✔️fixed unwanted scrollbars in UI

README.md, src/LaravelRequestDocsServiceProvider.php
Fixes #234 #238 
https://github.com/rakutentech/laravel-request-docs/issues/234#issuecomment-1573436230
=> publish assets for nginx users

ui/astro.config.mjs, ui/package.json
AstroCompress has been restored. This fixes it.
=> Restores astro-compress

src/Commands/ExportRequestDocsCommand.php
Added `sort` and `groupby` to the export command.
=> Add sort & groupby to export command

ui/src/components/elements/ApiActionInfo.tsx, ui/src/global.css, ui/src/libs/strings.tsx
Fixes #344 
Possibly Fixes #343 (I couldn't reproduce 343)
=> (ui) curl command should have backslash

ui/src/components/ApiAction.tsx, ui/src/components/elements/ApiActionResponse.tsx
=> Check response type if html to show html example of using dd() function
