composer.json, config/request-docs.php, src/LaravelRequestDocs.php
I needed that to generate route only for `/api/mobile` 
But existing `hide_matching` analyzes all routes anyway
=> Add ability to generate docs only for specific route uri prefix

resources/views/index.blade.php
The removed id is wrong because it's not for a specific route (it's outside of the `foreach` loop). Also, it causes a `ViewException` with the message `Undefined variable: doc`.
=> Remove id of default headers section

README.md, src/Attributes/RouteAttribute.php, src/Attributes/RouteDeprecated.php, src/Attributes/RouteDescription.php, src/LaravelRequestDocs.php, tests/RouteAttributeTest.php/RouteAttributeTest.php, tests/TestCase.php, tests/TestControllers/AttributesController.php
This PR adds functionality that requires php >= 8. Support for php 7.4 should still be okey.
Adding extra comments to a route using annotations in doc blocks can get somewhat bloated, and isn't very structured. It leaves it to every developer as to how to structure the comment.
By adding structured attributes it makes it a little easier to enforce a title and a description to any endpoint comment. Also, attributes could in the future be used to set other details about the route.
```php
#[RouteDescription('Title', 'Description')]
public function create(FooCreateRequest $request)
{
...
}
```
I have also added some tests to this. Since there were no tests to begin with there was nothing to build on. And there are no specific tests for the core functionality. The tests I added naturally …
=> Route comments using Attributes

README.md, src/LaravelRequestDocs.php
Hey there, 
I was working on my project and I needed some custom params to document my api, there wasn't any option so I implemented this idea, now we can add custom params in our controller method document.
Also we could not put custom lrd documents on methods that have not the request class, so I move it after the if statement.
Thanks for this amazing package.
=> Custom param rules and make lrd documents available for all route methods

src/LaravelRequestDocs.php
I have a problem that methods without params documents not shown, and now fixed
=> fix: method without params documents not shown

resources/views/index.blade.php
Hello, @kevincobain2000 
Remove unwanted tr (It generate extra space) after search result
=> Remove unwanted tr after search result

resources/views/index.blade.php, src/LaravelRequestDocs.php
1. GUI changes
2. Remove asset('./vendor/request-docs/dist/app.js')
3. Fix double listing routes with 2 methods
4. Add numeric data field fill, like integer
=> some fixes

config/request-docs.php, resources/views/index.blade.php
Hello, this PR is divided in 2 sections:
First of all I have fixed the id navigation on the endpoint body, the `href` reference wasn't generating the correct values and links on the URL field weren't working.
Second, I've added two configuration options:
- The ability to customize default headers. Very useful to speed up testing on different projects.
- The ability to hide development metadata. Key if the API docs are intended for public use, there's no need of showing folder structure nor class names.
I've kept the previous behaviour as default on the configuration files, but now they are overwritable.
=> Fix id navigation and add quality-of-life configuration options

src/LaravelRequestDocs.php
`continue;` do not skip the route because we are already in a foreach
`continue 2;` will skip it ! :)
=> fix bug not skipping duplicate routes

README.md, config/request-docs.php, src/Controllers/LaravelRequestDocsController.php, src/LaravelRequestDocs.php, tests/LRDTest.php, tests/TestControllers/UserController.php, ui/src/components/Sidebar.tsx, ui/src/components/TopNav.tsx
Close #121 
1. `api_uri`
2. `controller_full_path`
Check test `testGroupByURI` and `testGroupByFQController` for the group result.
Added `request-docs.group_by.uri_patterns` to group uri by the prefix.
=> Implement group feature

src/LaravelRequestDocs.php, tests/LRDTest.php
=> Sort docs by `group`, `group_index`

ui/README.md, ui/package-lock.json, ui/package.json, ui/src/components/ApiAction.tsx, ui/src/components/ApiInfo.tsx, ui/src/components/TopNav.tsx, ui/src/components/elements/ApiActionCurl.tsx, ui/src/components/elements/ApiActionInfo.tsx, ui/src/components/elements/ApiActionLog.tsx, ui/src/components/elements/ApiActionRequest.tsx, ui/src/components/elements/ApiActionResponse.tsx, ui/src/components/elements/ApiActionSQL.tsx, ui/src/components/elements/ApiActionTabs.tsx, ui/src/global.css
=> (v2.6) File uploads (single and multiple)

README.md, ui/src/components/ApiAction.tsx, ui/src/components/elements/ApiActionTabs.tsx, ui/src/global.css
=> (v2.9) allow empty json responses

config/request-docs.php, src/LaravelRequestDocs.php, src/LaravelRequestDocsServiceProvider.php, src/LaravelRequestDocsToOpenApi.php
Changes this PR has these changes for [BUG] #266 
1. **When exporting an OpenAPI3 JSON the Path Parameter values are also generated as query values**
2. **Excluding request body while generating the delete request. As OpenAPI3 discourages request body**
3. **Description Content added from configuration file**
4. **Exclude certain HTTP methods from exporting into JSON. Ex: `HEAD`**
=> Open API 3 Path Parameter & Delete Standard Rule Check Failed Issue Fixed  

config/request-docs.php, src/Commands/ExportRequestDocsCommand.php, src/LaravelRequestDocsServiceProvider.php
The PR will add an artisan command to export the same open API collection as an exportable JSON file.
using this feature people can generate API docs on the `GIt Action` or `CI/CD` workflow environment.
The artisan command will be `php artisan laravel-request-docs:export`
=> Artisan command to export collection as JSON file

README.md, src/Commands/ExportRequestDocsCommand.php
Fixes lint from https://github.com/rakutentech/laravel-request-docs/pull/294
=> lint fix and change log

src/LaravelRequestDocsFacade.php
**Problem**
Psalm inspection reports exception on projects that has `laravel-request-doc` as dependency
**To Reproduce**
Steps to reproduce the behavior:
1. `composer create-project laravel/laravel:^10.0 laravel`
2. `cd laravel-request-docs-test`
3. `composer require rakutentech/laravel-request-docs`
4. `composer require --dev vimeo/psalm -W`
5. `composer require --dev psalm/plugin-laravel -W`
6. Add a `psalm.xml` config file with following content:
```xml
<?xml version="1.0"?>
<psalm
findUnusedCode="true"
findUnusedBaselineEntry="true"
>
<projectFiles>
<directory name="src" />
</projectFiles>
</psalm>
```
7. `./vendor/bin/psalm-plugin enable psalm/plugin-laravel`
8. `./vendor/bin/psalm`
9. See in the output:
```
Exception: Target class [laravel-request-docs] does not exist.
Skipping …
```
=> Fix facade accessor

src/LaravelRequestDocsToOpenApi.php
Fixes an issue where the `@LRDResponses` annotation had no effect on the responses output in openapi docs.
@kevincobain2000 thx for the great package!
=> LaravelRequestDocsToOpenApi class gets the setAndFilterResponses method

config/request-docs.php, src/LaravelRequestDocsToOpenApi.php
This pull request will add a security scheme the collection is using globally.
1. **Security Type**: [HTTP Basic, HTTP Bearer, API KEY] if the value is set to null then remove the security section.
2. **Name**: if the security type is `apikey` then the name value will be used for query params or Header Key value.
3. **Position**: For security type is `apikey` then position value is used for setting where the API key will be positioned (Header/Query Param)
=> Security Section Added

.github/workflows/phplint.yml, .github/workflows/phptest.yml, composer.json, src/Doc.php, src/LaravelRequestDocsToOpenApi.php, src/RoutePath.php, tests/Controllers/LaravelRequestDocsControllerTest.php
This reverts commit fef812b6ebe86af5409f94cba695734b95fa7257.
=> Revert "Laravel 12.x Compatibility (#399)"
